language: node_js

before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload

script:
  - npm run check-config

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
